### ISSUE TITLE
vQFX interfaces keep writing to parquet even when there is nothing new

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#237] opened 2020-08-21 23:27 UTC
**Describe the bug**
vQFX using https://github.com/Juniper/vqfx10k-vagrant, the interfaces keep polling

```
jpietsch> interface show hostname=vqfx1 view=all
    ip6AddressList  master               timestamp    mtu  vlan                       type      ifname state                                      ipAddressList namespace hostname
0               []         2020-08-22 06:24:35.564   1986     0                    logical      bme0.0    up  [128.0.0.1/2, 128.0.0.4/2, 128.0.0.16/2, 128.0...       qfx    vqfx1
1              [-]    None 2020-08-22 06:24:35.564   2000     0                   ethernet        bme0    up                                                [-]       qfx    vqfx1
2              [-]    None 2020-08-22 06:24:35.564   9192     0                   ethernet        cbp0    up                                                [-]       qfx    vqfx1
3              [-]    None 2020-08-22 06:24:35.564  65536     0            software-pseudo         dsc    up                                                [-]       qfx    vqfx1
4               []         2020-08-22 06:24:35.564   1500     0                    logical       em0.0    up                                     [10.0.2.15/24]       qfx    vqfx1
5              [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet         em0    up                                                [-]       qfx    vqfx1
6               []         2020-08-22 06:24:35.564   1500     0                    logical       em1.0    up                                   [169.254.0.2/24]       qfx    vqfx1
7               []         2020-08-22 06:24:50.936   1500     0                    logical       em1.0    up                                   [169.254.0.2/24]       qfx    vqfx1
8               []         2020-08-22 06:25:06.169   1500     0                    logical       em1.0    up                                   [169.254.0.2/24]       qfx    vqfx1
9               []         2020-08-22 06:25:21.385   1500     0                    logical       em1.0    up                                   [169.254.0.2/24]       qfx    vqfx1
10              []         2020-08-22 06:25:36.597   1500     0                    logical       em1.0    up                                   [169.254.0.2/24]       qfx    vqfx1
11              []         2020-08-22 06:25:51.821   1500     0                    logical       em1.0    up                                   [169.254.0.2/24]       qfx    vqfx1
12              []         2020-08-22 06:26:07.062   1500     0                    logical       em1.0    up                                   [169.254.0.2/24]       qfx    vqfx1
13             [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet         em1    up                                                [-]       qfx    vqfx1
14             [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet         em1    up                                                [-]       qfx    vqfx1
15             [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet         em1    up                                                [-]       qfx    vqfx1
16             [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet         em1    up                                                [-]       qfx    vqfx1
17             [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet         em1    up                                                [-]       qfx    vqfx1
18             [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet         em1    up                                                [-]       qfx    vqfx1
19             [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet         em1    up                                                [-]       qfx    vqfx1
20              []         2020-08-22 06:24:35.564   1500     0                    logical   em2.32768    up                                   [192.168.1.2/24]       qfx    vqfx1
21              []         2020-08-22 06:24:50.936   1500     0                    logical   em2.32768    up                                   [192.168.1.2/24]       qfx    vqfx1
22              []         2020-08-22 06:25:06.169   1500     0                    logical   em2.32768    up                                   [192.168.1.2/24]       qfx    vqfx1
23              []         2020-08-22 06:25:21.385   1500     0                    logical   em2.32768    up                                   [192.168.1.2/24]       qfx    vqfx1
24              []         2020-08-22 06:25:36.597   1500     0                    logical   em2.32768    up                                   [192.168.1.2/24]       qfx    vqfx1
25              []         2020-08-22 06:25:51.821   1500     0                    logical   em2.32768    up                                   [192.168.1.2/24]       qfx    vqfx1
26              []         2020-08-22 06:26:07.062   1500     0                    logical   em2.32768    up                                   [192.168.1.2/24]       qfx    vqfx1
27             [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet         em2    up                                                [-]       qfx    vqfx1
28             [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet         em2    up                                                [-]       qfx    vqfx1
29             [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet         em2    up                                                [-]       qfx    vqfx1
30             [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet         em2    up                                                [-]       qfx    vqfx1
31             [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet         em2    up                                                [-]       qfx    vqfx1
32             [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet         em2    up                                                [-]       qfx    vqfx1
33             [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet         em2    up                                                [-]       qfx    vqfx1
34             [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet         em3    up                                                [-]       qfx    vqfx1
35             [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet         em3    up                                                [-]       qfx    vqfx1
36             [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet         em3    up                                                [-]       qfx    vqfx1
37             [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet         em3    up                                                [-]       qfx    vqfx1
38             [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet         em3    up                                                [-]       qfx    vqfx1
39             [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet         em3    up                                                [-]       qfx    vqfx1
40             [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet         em3    up                                                [-]       qfx    vqfx1
41              []         2020-08-22 06:24:35.564   1500     0                    logical   em4.32768    up                                     [192.0.2.2/24]       qfx    vqfx1
42              []         2020-08-22 06:24:50.936   1500     0                    logical   em4.32768    up                                     [192.0.2.2/24]       qfx    vqfx1
43              []         2020-08-22 06:25:06.169   1500     0                    logical   em4.32768    up                                     [192.0.2.2/24]       qfx    vqfx1
44              []         2020-08-22 06:25:21.385   1500     0                    logical   em4.32768    up                                     [192.0.2.2/24]       qfx    vqfx1
45              []         2020-08-22 06:25:36.597   1500     0                    logical   em4.32768    up                                     [192.0.2.2/24]       qfx    vqfx1
46              []         2020-08-22 06:25:51.821   1500     0                    logical   em4.32768    up                                     [192.0.2.2/24]       qfx    vqfx1
47              []         2020-08-22 06:26:07.062   1500     0                    logical   em4.32768    up                                     [192.0.2.2/24]       qfx    vqfx1
48             [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet         em4    up                                                [-]       qfx    vqfx1
49             [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet         em4    up                                                [-]       qfx    vqfx1
50             [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet         em4    up                                                [-]       qfx    vqfx1
51             [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet         em4    up                                                [-]       qfx    vqfx1
52             [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet         em4    up                                                [-]       qfx    vqfx1
53             [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet         em4    up                                                [-]       qfx    vqfx1
54             [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet         em4    up                                                [-]       qfx    vqfx1
55             [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet         em5    up                                                [-]       qfx    vqfx1
56             [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet         em5    up                                                [-]       qfx    vqfx1
57             [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet         em5    up                                                [-]       qfx    vqfx1
58             [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet         em5    up                                                [-]       qfx    vqfx1
59             [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet         em5    up                                                [-]       qfx    vqfx1
60             [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet         em5    up                                                [-]       qfx    vqfx1
61             [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet         em5    up                                                [-]       qfx    vqfx1
62             [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet         em6    up                                                [-]       qfx    vqfx1
63             [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet         em6    up                                                [-]       qfx    vqfx1
64             [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet         em6    up                                                [-]       qfx    vqfx1
65             [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet         em6    up                                                [-]       qfx    vqfx1
66             [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet         em6    up                                                [-]       qfx    vqfx1
67             [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet         em6    up                                                [-]       qfx    vqfx1
68             [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet         em6    up                                                [-]       qfx    vqfx1
69             [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet         em7    up                                                [-]       qfx    vqfx1
70             [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet         em7    up                                                [-]       qfx    vqfx1
71             [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet         em7    up                                                [-]       qfx    vqfx1
72             [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet         em7    up                                                [-]       qfx    vqfx1
73             [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet         em7    up                                                [-]       qfx    vqfx1
74             [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet         em7    up                                                [-]       qfx    vqfx1
75             [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet         em7    up                                                [-]       qfx    vqfx1
76             [-]    None 2020-08-22 06:24:35.564  65536     0                       vtep         esi    up                                                [-]       qfx    vqfx1
77             [-]    None 2020-08-22 06:24:35.564  65536     0  flexible-tunnel-interface        fti0    up                                                [-]       qfx    vqfx1
78             [-]    None 2020-08-22 06:24:35.564  65536     0                        gre    gr-0/0/0    up                                                [-]       qfx    vqfx1
79             [-]    None 2020-08-22 06:24:35.564  65536     0                        gre         gre    up                                                [-]       qfx    vqfx1
80             [-]    None 2020-08-22 06:24:35.564  65536     0                 ip-over-ip        ipip    up                                                [-]       qfx    vqfx1
81              []         2020-08-22 06:24:35.564   1500     0                    logical   irb.10000    up                   [10.10.1.251/24, 10.10.1.254/24]       qfx    vqfx1
82              []         2020-08-22 06:24:35.564   1500     0                    logical   irb.20000    up                   [10.10.2.251/24, 10.10.2.254/24]       qfx    vqfx1
83             [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet         irb    up                                                [-]       qfx    vqfx1
84              []         2020-08-22 06:24:35.564   1514     0                    logical      jsrv.1    up                                    [128.0.0.127/2]       qfx    vqfx1
85             [-]    None 2020-08-22 06:24:35.564   1514     0                    virtual        jsrv    up                                                [-]       qfx    vqfx1
86              []         2020-08-22 06:24:35.564  65536     0                    logical       lo0.0  down                                       [9.9.9.1/32]       qfx    vqfx1
87             [-]    None 2020-08-22 06:24:35.564  65536     0                   loopback         lo0    up                                                [-]       qfx    vqfx1
88             [-]    None 2020-08-22 06:24:35.564  65536     0                        lsi         lsi    up                                                [-]       qfx    vqfx1
89             [-]    None 2020-08-22 06:24:35.564  65536     0                        gre        mtun    up                                                [-]       qfx    vqfx1
90             [-]    None 2020-08-22 06:24:35.564      0     0                       None   pfe-0/0/0    up                                                [-]       qfx    vqfx1
91             [-]    None 2020-08-22 06:24:35.564      0     0                       None   pfh-0/0/0    up                                                [-]       qfx    vqfx1
92             [-]    None 2020-08-22 06:24:35.564  65536     0           pim-decapsulator        pimd    up                                                [-]       qfx    vqfx1
93             [-]    None 2020-08-22 06:24:35.564  65536     0           pim-encapsulator        pime    up                                                [-]       qfx    vqfx1
94             [-]    None 2020-08-22 06:24:35.564   9192     0                   ethernet        pip0    up                                                [-]       qfx    vqfx1
95             [-]    None 2020-08-22 06:24:35.564  65536     0                        tap         tap    up                                                [-]       qfx    vqfx1
96             [-]    None 2020-08-22 06:24:35.564   1514     0                  mgmt-vlan         vme  down                                                [-]       qfx    vqfx1
97              []         2020-08-22 06:24:35.564  65536     0                    logical  vtep.32769    up                                                 []       qfx    vqfx1
98             [-]    None 2020-08-22 06:24:35.564  65536     0                       vtep        vtep    up                                                [-]       qfx    vqfx1
99              []         2020-08-22 06:24:35.564   1500     0                    logical  xe-0/0/0.0    up                                      [10.0.0.1/30]       qfx    vqfx1
100             []         2020-08-22 06:24:50.936   1500     0                    logical  xe-0/0/0.0    up                                      [10.0.0.1/30]       qfx    vqfx1
101             []         2020-08-22 06:25:06.169   1500     0                    logical  xe-0/0/0.0    up                                      [10.0.0.1/30]       qfx    vqfx1
102             []         2020-08-22 06:25:21.385   1500     0                    logical  xe-0/0/0.0    up                                      [10.0.0.1/30]       qfx    vqfx1
103             []         2020-08-22 06:25:36.597   1500     0                    logical  xe-0/0/0.0    up                                      [10.0.0.1/30]       qfx    vqfx1
104             []         2020-08-22 06:25:51.821   1500     0                    logical  xe-0/0/0.0    up                                      [10.0.0.1/30]       qfx    vqfx1
105             []         2020-08-22 06:26:07.062   1500     0                    logical  xe-0/0/0.0    up                                      [10.0.0.1/30]       qfx    vqfx1
106            [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet    xe-0/0/0    up                                                [-]       qfx    vqfx1
107            [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet    xe-0/0/0    up                                                [-]       qfx    vqfx1
108            [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet    xe-0/0/0    up                                                [-]       qfx    vqfx1
109            [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet    xe-0/0/0    up                                                [-]       qfx    vqfx1
110            [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet    xe-0/0/0    up                                                [-]       qfx    vqfx1
111            [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet    xe-0/0/0    up                                                [-]       qfx    vqfx1
112            [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet    xe-0/0/0    up                                                [-]       qfx    vqfx1
113             []         2020-08-22 06:24:35.564   1514     0                    logical  xe-0/0/1.0    up                                                 []       qfx    vqfx1
114             []         2020-08-22 06:24:50.936   1514     0                    logical  xe-0/0/1.0    up                                                 []       qfx    vqfx1
115             []         2020-08-22 06:25:06.169   1514     0                    logical  xe-0/0/1.0    up                                                 []       qfx    vqfx1
116             []         2020-08-22 06:25:21.385   1514     0                    logical  xe-0/0/1.0    up                                                 []       qfx    vqfx1
117             []         2020-08-22 06:25:36.597   1514     0                    logical  xe-0/0/1.0    up                                                 []       qfx    vqfx1
118             []         2020-08-22 06:25:51.821   1514     0                    logical  xe-0/0/1.0    up                                                 []       qfx    vqfx1
119             []         2020-08-22 06:26:07.062   1514     0                    logical  xe-0/0/1.0    up                                                 []       qfx    vqfx1
120            [-]  bridge 2020-08-22 06:24:35.564   1514     0                   ethernet    xe-0/0/1    up                                                [-]       qfx    vqfx1
121            [-]  bridge 2020-08-22 06:24:50.936   1514     0                   ethernet    xe-0/0/1    up                                                [-]       qfx    vqfx1
122            [-]  bridge 2020-08-22 06:25:06.169   1514     0                   ethernet    xe-0/0/1    up                                                [-]       qfx    vqfx1
123            [-]  bridge 2020-08-22 06:25:21.385   1514     0                   ethernet    xe-0/0/1    up                                                [-]       qfx    vqfx1
124            [-]  bridge 2020-08-22 06:25:36.597   1514     0                   ethernet    xe-0/0/1    up                                                [-]       qfx    vqfx1
125            [-]  bridge 2020-08-22 06:25:51.821   1514     0                   ethernet    xe-0/0/1    up                                                [-]       qfx    vqfx1
126            [-]  bridge 2020-08-22 06:26:07.062   1514     0                   ethernet    xe-0/0/1    up                                                [-]       qfx    vqfx1
127            [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet   xe-0/0/10    up                                                [-]       qfx    vqfx1
128            [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet   xe-0/0/10    up                                                [-]       qfx    vqfx1
129            [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet   xe-0/0/10    up                                                [-]       qfx    vqfx1
130            [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet   xe-0/0/10    up                                                [-]       qfx    vqfx1
131            [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet   xe-0/0/10    up                                                [-]       qfx    vqfx1
132            [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet   xe-0/0/10    up                                                [-]       qfx    vqfx1
133            [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet   xe-0/0/10    up                                                [-]       qfx    vqfx1
134            [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet   xe-0/0/11    up                                                [-]       qfx    vqfx1
135            [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet   xe-0/0/11    up                                                [-]       qfx    vqfx1
136            [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet   xe-0/0/11    up                                                [-]       qfx    vqfx1
137            [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet   xe-0/0/11    up                                                [-]       qfx    vqfx1
138            [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet   xe-0/0/11    up                                                [-]       qfx    vqfx1
139            [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet   xe-0/0/11    up                                                [-]       qfx    vqfx1
140            [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet   xe-0/0/11    up                                                [-]       qfx    vqfx1
141             []         2020-08-22 06:24:35.564   1514     0                    logical  xe-0/0/2.0    up                                                 []       qfx    vqfx1
142             []         2020-08-22 06:24:50.936   1514     0                    logical  xe-0/0/2.0    up                                                 []       qfx    vqfx1
143             []         2020-08-22 06:25:06.169   1514     0                    logical  xe-0/0/2.0    up                                                 []       qfx    vqfx1
144             []         2020-08-22 06:25:21.385   1514     0                    logical  xe-0/0/2.0    up                                                 []       qfx    vqfx1
145             []         2020-08-22 06:25:36.597   1514     0                    logical  xe-0/0/2.0    up                                                 []       qfx    vqfx1
146             []         2020-08-22 06:25:51.821   1514     0                    logical  xe-0/0/2.0    up                                                 []       qfx    vqfx1
147             []         2020-08-22 06:26:07.062   1514     0                    logical  xe-0/0/2.0    up                                                 []       qfx    vqfx1
148            [-]  bridge 2020-08-22 06:24:35.564   1514     0                   ethernet    xe-0/0/2    up                                                [-]       qfx    vqfx1
149            [-]  bridge 2020-08-22 06:24:50.936   1514     0                   ethernet    xe-0/0/2    up                                                [-]       qfx    vqfx1
150            [-]  bridge 2020-08-22 06:25:06.169   1514     0                   ethernet    xe-0/0/2    up                                                [-]       qfx    vqfx1
151            [-]  bridge 2020-08-22 06:25:21.385   1514     0                   ethernet    xe-0/0/2    up                                                [-]       qfx    vqfx1
152            [-]  bridge 2020-08-22 06:25:36.597   1514     0                   ethernet    xe-0/0/2    up                                                [-]       qfx    vqfx1
153            [-]  bridge 2020-08-22 06:25:51.821   1514     0                   ethernet    xe-0/0/2    up                                                [-]       qfx    vqfx1
154            [-]  bridge 2020-08-22 06:26:07.062   1514     0                   ethernet    xe-0/0/2    up                                                [-]       qfx    vqfx1
155            [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet    xe-0/0/3    up                                                [-]       qfx    vqfx1
156            [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet    xe-0/0/3    up                                                [-]       qfx    vqfx1
157            [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet    xe-0/0/3    up                                                [-]       qfx    vqfx1
158            [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet    xe-0/0/3    up                                                [-]       qfx    vqfx1
159            [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet    xe-0/0/3    up                                                [-]       qfx    vqfx1
160            [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet    xe-0/0/3    up                                                [-]       qfx    vqfx1
161            [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet    xe-0/0/3    up                                                [-]       qfx    vqfx1
162            [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet    xe-0/0/4    up                                                [-]       qfx    vqfx1
163            [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet    xe-0/0/4    up                                                [-]       qfx    vqfx1
164            [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet    xe-0/0/4    up                                                [-]       qfx    vqfx1
165            [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet    xe-0/0/4    up                                                [-]       qfx    vqfx1
166            [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet    xe-0/0/4    up                                                [-]       qfx    vqfx1
167            [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet    xe-0/0/4    up                                                [-]       qfx    vqfx1
168            [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet    xe-0/0/4    up                                                [-]       qfx    vqfx1
169            [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet    xe-0/0/5    up                                                [-]       qfx    vqfx1
170            [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet    xe-0/0/5    up                                                [-]       qfx    vqfx1
171            [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet    xe-0/0/5    up                                                [-]       qfx    vqfx1
172            [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet    xe-0/0/5    up                                                [-]       qfx    vqfx1
173            [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet    xe-0/0/5    up                                                [-]       qfx    vqfx1
174            [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet    xe-0/0/5    up                                                [-]       qfx    vqfx1
175            [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet    xe-0/0/5    up                                                [-]       qfx    vqfx1
176            [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet    xe-0/0/6    up                                                [-]       qfx    vqfx1
177            [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet    xe-0/0/6    up                                                [-]       qfx    vqfx1
178            [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet    xe-0/0/6    up                                                [-]       qfx    vqfx1
179            [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet    xe-0/0/6    up                                                [-]       qfx    vqfx1
180            [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet    xe-0/0/6    up                                                [-]       qfx    vqfx1
181            [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet    xe-0/0/6    up                                                [-]       qfx    vqfx1
182            [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet    xe-0/0/6    up                                                [-]       qfx    vqfx1
183            [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet    xe-0/0/7    up                                                [-]       qfx    vqfx1
184            [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet    xe-0/0/7    up                                                [-]       qfx    vqfx1
185            [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet    xe-0/0/7    up                                                [-]       qfx    vqfx1
186            [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet    xe-0/0/7    up                                                [-]       qfx    vqfx1
187            [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet    xe-0/0/7    up                                                [-]       qfx    vqfx1
188            [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet    xe-0/0/7    up                                                [-]       qfx    vqfx1
189            [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet    xe-0/0/7    up                                                [-]       qfx    vqfx1
190            [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet    xe-0/0/8    up                                                [-]       qfx    vqfx1
191            [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet    xe-0/0/8    up                                                [-]       qfx    vqfx1
192            [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet    xe-0/0/8    up                                                [-]       qfx    vqfx1
193            [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet    xe-0/0/8    up                                                [-]       qfx    vqfx1
194            [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet    xe-0/0/8    up                                                [-]       qfx    vqfx1
195            [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet    xe-0/0/8    up                                                [-]       qfx    vqfx1
196            [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet    xe-0/0/8    up                                                [-]       qfx    vqfx1
197            [-]    None 2020-08-22 06:24:35.564   1514     0                   ethernet    xe-0/0/9    up                                                [-]       qfx    vqfx1
198            [-]    None 2020-08-22 06:24:50.936   1514     0                   ethernet    xe-0/0/9    up                                                [-]       qfx    vqfx1
199            [-]    None 2020-08-22 06:25:06.169   1514     0                   ethernet    xe-0/0/9    up                                                [-]       qfx    vqfx1
200            [-]    None 2020-08-22 06:25:21.385   1514     0                   ethernet    xe-0/0/9    up                                                [-]       qfx    vqfx1
201            [-]    None 2020-08-22 06:25:36.597   1514     0                   ethernet    xe-0/0/9    up                                                [-]       qfx    vqfx1
202            [-]    None 2020-08-22 06:25:51.821   1514     0                   ethernet    xe-0/0/9    up                                                [-]       qfx    vqfx1
203            [-]    None 2020-08-22 06:26:07.062   1514     0                   ethernet    xe-0/0/9    up                                                [-]       qfx    vqfx1 
```

**Comment by ddutt** [comment] 2020-08-23 18:52
Fixed with the commit 9526d4e647633cb845b600d64b1628726eb071dc

This issue was caused by jitter introduced because of the field we used to compute the last time the interface state changed.

**Closed by ddutt** 2020-08-23 18:52 UTC
Labels: bug
