### ISSUE TITLE
add support to username/password as globally defined variables

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#325] opened 2021-03-03 08:00 UTC
add support to:

```
user: NoTmYuSeR
pass: NoTmYpAsSwOrD
- namespace: NAME
  hosts:
    - url: ssh://192.168.157.5 username={{user}} password={{pass}}
    - url: ssh://192.168.157.6 username={{user}} password={{pass}}
    - url: ssh://192.168.157.7 username={{user}} password={{pass}}
    - url: ssh://192.168.157.8 username={{user}} password={{pass}}
- namespace: SPACE
  hosts:
    - url: ssh://192.168.157.9 username={{user}} password={{pass}}
    - url: ssh://192.168.157.10 username={{user}} password={{pass}}
    - url: ssh://192.168.157.11 username={{user}} password={{pass}}
    - url: ssh://192.168.157.12 username={{user}} password={{pass}}
```

or to:

```
- namespace: NAME
  user1: NoTmYuSeR
  pass1: NoTmYpAsSwOrD
  hosts:
    - url: ssh://192.168.157.5 username={{user1}} password={{pass1}}
    - url: ssh://192.168.157.6 username={{user1}} password={{pass1}}
    - url: ssh://192.168.157.7 username={{user1}} password={{pass1}}
    - url: ssh://192.168.157.8 username={{user1}} password={{pass1}}
- namespace: SPACE
  user2: NoTmYuSeR
  pass2: NoTmYpAsSwOrD
  hosts:
    - url: ssh://192.168.157.9 username={{user2}} password={{pass2}}
    - url: ssh://192.168.157.10 username={{user2}} password={{pass2}}
    - url: ssh://192.168.157.11 username={{user2}} password={{pass2}}
    - url: ssh://192.168.157.12 username={{user2}} password={{pass2}}
```

right now, the first case, cases sq-poller to crash, the second doesn't crash bu the poller won't connect anyway

**Comment by ddutt** [comment] 2021-03-29 12:48
DO we need this since you'll no longer be using this, but the solution suggested by #308

**Comment by anubisg1** [comment] 2021-03-29 12:56
What's the proposed implementation for #308? I guess it depends just from that. But I agree, if done right, this would be redundant

**Comment by ddutt** [comment] 2021-03-30 03:13
Duplicate of #308

**Closed by ddutt** 2021-03-30 03:13 UTC
