### ISSUE TITLE
Collect MST data

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#547] opened 2022-01-06 17:43 UTC
The need to collect Spanning Tree data is important for vxlan and not vxlan environments.

For vxlan environments it's required because the vteps still speak STP towards downstream interfaces.

MST is created as a separate request because it isn't as common as rpvst/rpvst+

**Comment by ddutt** [comment] 2022-04-15 16:54
Duplicate of #328

**Closed by ddutt** 2022-04-15 16:54 UTC
