### ISSUE TITLE
Devconfig not returning Config

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#665] opened 2022-03-28 22:29 UTC
**Describe the bug**
When running `devconfig show` Im not getting the configuration back.
```
root> devconfig show hostname="leaf1-ios"
show ipv6 interface
leaf1-ios#
root>
```

**To Reproduce**
Go to the CLI and type: `devconfig show`

**Attach**
TBC

 **Expected behavior**
TBC

**Screenshots**
TBC

**Additional context**
* version 0.17.0rc1
* occurs on remote and direct DB CLI.

**Comment by ddutt** [comment] 2022-04-13 15:41
Duplicate of #639

**Closed by ddutt** 2022-04-13 15:41 UTC
