### ISSUE TITLE
route lpm address isn't working

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#198] opened 2020-06-30 15:04 UTC
route lpm doesn't return any data, but data is available and route show prefix works well

```
root> route lpm address="10.14.255.131"                   
Empty DataFrame
Columns: [default]
Index: []
root> route show prefix="10.14.255.131/32"                
      namespace                hostname      vrf            prefix        nexthopIps       oifs protocol source  metric  ipvers   action               timestamp
59691    LAB  		leaf-101.lab.com   LR1_dmz  10.14.255.131/32  [10.154.191.111]         []      bgp              0       4  forward 2020-06-29 16:40:02.434
60353    LAB  		leaf-102.lab.com   LR1_dmz  10.14.255.131/32  [10.154.191.111]         []      bgp              0       4  forward 2020-06-29 16:40:02.087
61015    LAB  		leaf-103.lab.com   LR1_dmz  10.14.255.131/32   [10.14.255.131]  [Vlan607]      hmm              0       4  forward 2020-06-29 16:40:02.288
61677    LAB  		leaf-104.lab.com   LR1_dmz  10.14.255.131/32   [10.14.255.131]  [Vlan607]      hmm              0       4  forward 2020-06-29 16:40:02.173
root>  
```

**Comment by ddutt** [comment] 2020-07-04 22:08
The bug here is that without any VRF specification, lpm only looks for routes in the default VRF. This is unlike other commands such as BGP and OSPF where the absence of a VRF specification implies all VRFs. lpm itself is working fine.

**Comment by ddutt** [comment] 2020-07-13 01:15
Duplicate of #214

**Closed by ddutt** 2020-07-13 01:15 UTC
Labels: bug
