### ISSUE TITLE
evpnVni assert asserts with multidc data

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#251] opened 2020-09-09 22:16 UTC
**Describe the bug**
```
(suzieq-QZqWZG2D-py3.8) jpietsch@jpietsch-server:~/suzieq$ suzieq/cli/suzieq-cli -c ~/configs/multidc.yml evpnVni assert
Error running command: 'Load' object has no attribute '__name__'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/src/python-nubia/nubia/internal/cmdbase.py", line 446, in run_cli
    return fn(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/cli/sqcmds/EvpnVniCmd.py", line 62, in aver
    df = self.sqobj.aver(
  File "/home/jpietsch/suzieq/suzieq/sqobjects/evpnVni.py", line 24, in aver
    return self.engine_obj.aver(**kwargs)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/evpnVni.py", line 177, in aver
    her_df["assertReason"] += her_df.apply(
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/apply.py", line 313, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/apply.py", line 341, in apply_series_generator
    results[i] = self.f(v)
  File "/home/jpietsch/suzieq/suzieq/engines/pandas/evpnVni.py", line 268, in _is_vtep_reachable
    route = self._routes_df \
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 3231, in query
    res = self.eval(expr, **kwargs)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 3346, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 332, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 764, in __init__
    self.terms = self.parse()
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 781, in parse
    return self._visitor.visit(self.expr)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 381, in visit_Module
    return self.visit(expr, **kwargs)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 384, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 622, in visit_Call
    res = self.visit_Attribute(node.func)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 607, in visit_Attribute
    resolved = self.visit(value).value
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 375, in visit
    return visitor(node, **kwargs)
  File "/home/jpietsch/.cache/pypoetry/virtualenvs/suzieq-QZqWZG2D-py3.8/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 617, in visit_Attribute
    raise ValueError(f"Invalid Attribute context {ctx.__name__}")
AttributeError: 'Load' object has no attribute '__name__'
------------------------------------------------------------
```

**Comment by ddutt** [comment] 2020-09-20 06:08
This was caused by a reference to the obsoleted cyberpandas package. Fixed with commit ce68ca78135e3c28831e34c1c6d468069146bbd6

**Closed by ddutt** 2020-09-20 06:08 UTC
Labels: bug
