### ISSUE TITLE
Differential of DevConfig using Time Analysis

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#589] opened 2022-01-31 20:35 UTC
**Is your feature request related to a problem? Please describe.**
When performing a devconfig, it would be great to be able to use an endtime, then show the differences between the 2 times, i.e what has been added and removed in the config.

**Comment by ddutt** [comment] 2022-04-15 16:46
Duplicate of #436

**Closed by ddutt** 2022-04-15 16:46 UTC
