### ISSUE TITLE
IOSXR branch, GUI, path and click on first link gets an exception

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#349] opened 2021-03-23 22:46 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/57378043/112228717-f5f6c680-8bee-11eb-9e86-cafb00131fe0.png)

**Comment by ddutt** [comment] 2021-03-29 12:39
Can't reproduce. Maybe fixed via 1277a5e52928df6d58ff6834995bdefebe3fd7b6?

**Comment by jopietsch** [comment] 2021-03-29 16:51
I think it's fixed, but it's not from 1277a5e.

**Comment by jopietsch** [comment] 2021-03-31 20:48
it's not fixed

**Comment by jopietsch** [comment] 2021-03-31 20:51
it's not just that first link.

**Closed** 2021-03-31 21:11 UTC
Labels: bug
